### ISSUE TITLE
Scrollback Chrome Extension is no longer working

### ISSUE THREAD

**Issue by abbaspaliwala** [jezcope/chrome-scroll-back#1]
Scrollback Chrome Extension is no longer working.

Chrome Version is 55.0.2883.87 m (64-bit).

**Comment by abbaspaliwala** [comment]
Scrollback Chrome Extension is no longer working #1

**Comment by jezcope** [comment]
Thanks for reporting this — looks like @mylibero has submitted a PR with the request so I'll get it sorted out. I had no idea people were actually using this! :grinning:

**Comment by jezcope** [comment]
Fixed by #2 and I've uploaded the new version to the web store — it might take up to an hour to become available.

**Comment by abbaspaliwala** [comment]
Excellent! Thanks.

**Comment by abbaspaliwala** [comment]
The availability of this extension is one of the main reasons I finally decided to switch from Firefox to Chrome.  But when it stopped working, I seriously though about switching back! 

But your updated version works great !

Thanks again.

**Comment by mylibero** [comment]
Thanks for merging it and updating the extension. 
Finally I can use chrome in the non-dev mode. :)
